docs: Add translation based enhancement for upgrade card
mitodl/frontend-app-learning pull request #3
Opened 2022-06-20 11:44 UTC by arslanashraf7

#### Related Ticket:
https://github.com/mitodl/mitxonline/issues/556

#### What this PR does?
- This PR adds translation overrides for the English language
- Updates the `Upgrade` course card to reflect the overridden changes in the newly added `en.json`

#### Screenshots:

**Desktop**

<img width="1669" alt="Screenshot 2022-06-20 at 4 42 31 PM" src="https://user-images.githubusercontent.com/34372316/174594411-a4b6bf21-9581-4ea5-9616-d814bc7b77a1.png">

**Mobile**

<img width="495" alt="Screenshot 2022-06-20 at 4 42 43 PM" src="https://user-images.githubusercontent.com/34372316/174594435-d6cc75d6-ff36-4065-a432-a6423914eb94.png">

2022-06-20 18:31 UTC, arslanashraf7 commented on src/setupTest.js
> +    messages: [delete appMessages.en],
This change was required to pass the test in CI. Since the tests that match texts in different fields are hardcoded in the app e.g. [this](https://github.com/mitodl/frontend-app-learning/blob/master/src/generic/upgrade-notification/UpgradeNotification.test.jsx#L52-L55). 

And since we added a language file the test try to match these hard-coded ones against them so I had to remove the `en` language from the messages just for the tests.

2022-06-20 18:35 UTC, arslanashraf7 commented
This is the PR that implements what we discussed in other PR [in this comment](https://github.com/mitodl/frontend-app-learning/pull/2#issuecomment-1155623589). I didn't update that PR with these changes since we might want to keep that for cross-referencing where we took another approach to achieve the exact design.

This PR only plays around with the translation to keep the impact of changes low.

Also, I divided the description text [mentioned here](https://github.com/mitodl/frontend-app-learning/pull/2#issuecomment-1150462844) into two bullets because those bullets are part of JSX/HTML which we won't change. The screenshots of the resulting look and feel have been added to the PR description.

Let me know what you think of this @pdpinch

2022-06-20 20:48 UTC, rhysyngsun commented on src/setupTest.js
> +    messages: [delete appMessages.en],
Are you able to conditionally include `en` in `appMessages` if `process.env.NODE_ENV != "test" instead?

2022-06-21 07:05 UTC, arslanashraf7 commented on src/setupTest.js
> +    messages: [delete appMessages.en],
Yes, If we don't want it in TestSetup here, think we should be able to do it and that change would be done in `index.jsx`.  Let me try a few ways on that.

2022-06-21 14:31 UTC, rhysyngsun requested changes
Looks good, can you merge to the branch `open-learning` that I made that way we can leave `master` pristine for easier rebases?

2022-06-22 08:00 UTC, arslanashraf7 commented
> Looks good, can you merge to the branch `open-learning` that I made that way we can leave `master` pristine for easier rebases?

Yes, that's reasonable correct. I've changed the base branch to be `open-learning` for the merge.

2022-06-22 10:45 UTC, merged